export const ERROR_CODES = {
    AUTH_REQUIRED: 'AUTH_REQUIRED',
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
    AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',

    ACCESS_DENIED: 'ACCESS_DENIED',

    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_AMOUNT: 'INVALID_AMOUNT',
    INVALID_LIMITS: 'INVALID_LIMITS',

    ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
    ACCOUNT_ALREADY_FROZEN: 'ACCOUNT_ALREADY_FROZEN',
    ACCOUNT_NOT_FROZEN: 'ACCOUNT_NOT_FROZEN',

    DEPOSIT_NOT_FOUND: 'DEPOSIT_NOT_FOUND',
    DEPOSIT_INVALID_STATUS: 'DEPOSIT_INVALID_STATUS',
    DEPOSIT_REVERT_WINDOW_EXPIRED: 'DEPOSIT_REVERT_WINDOW_EXPIRED',

    TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
    TRANSFER_REVERT_WINDOW_EXPIRED: 'TRANSFER_REVERT_WINDOW_EXPIRED',

    INTERNAL_ERROR: 'INTERNAL_ERROR',
    NOT_FOUND: 'NOT_FOUND'
};
